language: rust

cache: cargo

rust:
  - nightly

notifications:
  irc:
    channels:
      - "irc.rizon.net#aggvistnurummor"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{commit_subject} - %{author}): %{message} (%{elapsed_time})"
